#include <iostream>
#include <bitset>     
#include <font.h>    
#include <string>    
#include <cmath>       
#include <algorithm>   
#include <utility>      
#include <iterator>     
#include <iomanip>      
